# Generated by Django 5.0.6 on 2024-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField(unique=True)),
                ('sentiment', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
